title: San's Blog
description: > # this means to ignore newlines until "baseurl:"
  San's blog, mostly technical write-ups.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://sanspace.in" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: 2sks #if your site has a twitter account, enter it here

# Author Settings
author: San # add your name
author-img: San.jpg # add your photo
about-author: I am a Solutions Architect and a Full Stack Developer. Always looking to learn and teach. # add description
social-twitter: 2sks # add your Twitter handle
social-stackoverflow: sanspace # add your Facebook handle
social-github: sanspace # add your Github handle
social-linkedin: santhoshkumarsrinivasan # add your Linkedin handle
social-email: san@sanspace.in # add your Email address

# Disqus
discus-identifier: sanspace-blog # add your discus identifier

# Tracker
analytics: UA-17248968-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
